services:
  - type: web
    name: hyperlocal-backend
    env: python
    region: singapore   # change to: oregon, ohio, frankfurt, or virginia
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hyperlocal-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 43200
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: APP_URL
        value: https://hyperlocal-backend-8ixl.onrender.com
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false


databases:
  - name: hyperlocal-db
    plan: free
    region: singapore   # must match the service region above
